n_hops: 2
neighbors_hops: True
cf_beta: 0.8
fair_beta: 0.5
cf_epochs: 100
# device: cpu

sub_matrix_only_last_level: False
not_user_sub_matrix: False
only_subgraph: False

explain_fairness: False
explain_fairness_NDCGApprox: False
sensitive_attributes: [gender] # , age]

cf_optimizer: SGD
cf_learning_rate: 2

keep_history_if_possible: False

# only useful for hops analysis
explainer_force_return: False
# ML-100K
load_col:
    inter: [user_id, item_id, timestamp]
    item: [item_id, class]
    user: [user_id, gender, age]

# ML-1M
#load_col:
#    inter: [user_id, item_id, timestamp]
#    item: [item_id, genre]
#    user: [user_id, gender, age]
